### ISSUE TITLE
[idea] auto sleeping server and restart when someone joins

### ISSUE THREAD

**Issue by Unkn0wnCreator** [ich777/docker-minecraft-basic-server#10]
I think it would be great to use this: https://github.com/vincss/mcsleepingserverstarter
within this docker, because many people want an small server for them and there friends and for that the Minecraft server does not need to be running at all times but should be accessible without calling or texting please start the server.

**Comment by ich777** [comment]
Does the dedicated server produce such high loads your server when nobody is playing?

I know the concept of sleeping MC servers but my container was designed without that in mind and actually never wanted to use this feature because it gave me some issues in the past (server not waking up, server crashing,...) .
You could always use something like [AMP](https://cubecoders.com/AMP) that supports sleeping MC servers but I always see such solutions more as a workaround and experimental.

Sorry but I don't want to integrate MC server sleeping into my container. Hope you understand that.
If you are using unRAID AMP is also available through the CA App [Click](https://unraid.net/community/apps?notTheDroidYoureLookingFor=d2FlcmNldXZsZXBrYW5qc2F5bWx1bGJvcXFlanJlamI%3D&q=cubecoders+amp#r)

**Comment by Unkn0wnCreator** [comment]
no problem:) i only thought it could be interesting not because of cpu but ram
