### ISSUE TITLE
Issue with Memory Allocation

### ISSUE THREAD

**Issue by itanne99** [ich777/docker-minecraft-basic-server#2]
I have a couple docker containers set up for my servers and they all run into the same problem. Being which none of them actually take the set memory to them and use the default memory size. 
![image](https://user-images.githubusercontent.com/20746427/85433507-89ad4080-b552-11ea-9af7-e117f4930fc1.png)

_I'm assuming since the modpack needs more then the default memory size it overrides this, but I set the container to use a minimum of 6GB when it's only using 3GB_

**Comment by ich777** [comment]
I don't understand exactly what you mean. Are these all Minecraft containers? Did you mean that it uses only 3GB if you set it to a maximum of 6GB?

**Comment by itanne99** [comment]
So with this specific container. Which is it's own server. I have it set to use a minimum of 6gb of ram, but for some reason it's only using the default minimum ram

**Comment by ich777** [comment]
Yes because a Docker container is not a VM and you only set the maximum RAM that it can consume, if it doesn't need 6GB of RAM it doesn't take it.
It only takes it if it needs it for example when you have much players on your server but keep in mind that if it needs mor then 6GB you can run into problems and the server or plugins can crash.

**Comment by itanne99** [comment]
yea that makes sense. Alright so then why is there an option for minimum ram in the container settings?
It's labeled XMS

**Comment by ich777** [comment]
> The minimum size indicates to the JVM to allocate this size of memory freely. It still does some resource tidying but it will consume the amount of memory you give it fairly quickly given half a chance. However, it still won't allocate the memory until it has a use for it. Note: it will allocate virtual memory immediately. 

It's the the answer under the first question: [Resource](https://stackoverflow.com/questions/3876257/java-option-xms-is-not-applied-immediately)

As I said above it's not like a Virtual Machine works, the JVM won't allocate the RAM imediately if it doesn't needs it.
That's the cool thing about Docker, it shares resources and therefore it's (usually) possible to run more Containers in parallel than VMs on the same machine because they only take resources if they need it.

**Comment by itanne99** [comment]
Alrighty well thank you. Everything you're saying makes sense to me

**Comment by ich777** [comment]
Glad to help ;)
