### ISSUE TITLE
chown: cannot access '/tmp/server.properties': No such file or directory

### ISSUE THREAD

**Issue by mgutt** [ich777/docker-minecraft-basic-server#6]
Container throws these errors:
```
---Starting...---
chown: cannot access '/tmp/server.properties': No such file or directory
chmod: cannot access '/tmp/server.properties': No such file or directory
---Checking for 'runtime' folder---
```
I think this happens because of this line:
https://github.com/ich777/docker-minecraft-basic-server/blob/master/Dockerfile#L39

Shouldn't it be?
```
COPY /serverdata/serverfiles/server.properties /tmp/server.properties
```

**Comment by ich777** [comment]
> Shouldn't it be?

No because actually it copies the files from the build directory (the Git repo) to the container itself.

I think it's because of your guide, if you done this in this container too: [Click](https://forums.unraid.net/topic/112617-ssd-abnutzung-ma%C3%9Fgeblich-reduzieren/)

In your guide at "Gegenmaßnahmen" at Step 4 you wrote:
> Nun tragen wir "/tmp" beim "Container Path" ein und "/tmp/<containername>" beim "Host Path"

If you do this, you basically wipe everything in the `/tmp` directory inside the container and therefore the file `server.properties` isn't there anymore.
I ship this file as a template for new installations in the `/tmp` directory that is copied over to the main directory if it's not found.

We now have two or better speaking three options:
1. Ignore the error
2. I can add 2>/dev/null to the line where it chmod's the file so that you have no output
3. Change the files location inside the container (but that's actually something that I really don't want to do)

**Comment by ich777** [comment]
@mgutt can this be closed?
