### ISSUE TITLE
Environment Variable RUNTIME_NAME not being respected

### ISSUE THREAD

**Issue by Airyzz** [ich777/docker-minecraft-basic-server#8]
I've been trying to set up a FTB Revelations server, which requires basicjre. However when I set RUNTIME_NAME to 'basicjre', jre16 is installed. For now I just installed the runtime manually.

**Comment by ich777** [comment]
> For now I just installed the runtime manually.

If you change the `RUNTIME_NAME` you have to delete the `runtime` folder manually:
1. Stop the container
2. Remove the `runtime` folder from your Minecraft directory
3. Start the container
4. Runtime will be downloaded

Nothing is implemented in the container to remove the old `jre` since it was never intended to be used like this.

I think you only have changed the variable or am I wrong?

**Comment by Airyzz** [comment]
I did delete the folder, and it would still download jre16

**Comment by ich777** [comment]
@Airyzz I've tested this back and forth with a new installation:
Here are the logs:

1. I changed the `RUNTIME_NAME` to `basicjre` before starting so that it downloads it instead of `jre16` [1-Minecraft_basicjre.log](https://github.com/ich777/docker-minecraft-basic-server/files/7495531/1-Minecraft_basicjre.log)
2. I stopped the container and deleted the `runtime` folder and changed `RUNTIME_NAME` to `jre16` so that it downloads it instead of `basicjre` [2-Minecraft_jre16.log](https://github.com/ich777/docker-minecraft-basic-server/files/7495541/2-Minecraft_jre16.log)
3. I stopped the container and deleted the `runtime` folder once again and changed the `RUNTIME_NAME` to `basicjre` so that it download again instead of `jre16` [3-Minecraft_basicjre.log](https://github.com/ich777/docker-minecraft-basic-server/files/7495555/3-Minecraft_basicjre.log)

As you can see from the logs everything is working as expected.
Are you sure that you've stopped the container in the first place and deleted the whole `runtime` folder:
![screenshot](https://user-images.githubusercontent.com/28066518/140713750-a96c027f-540e-4eaf-8fc6-19087e6d687e.png)

**Comment by Airyzz** [comment]
@ich777 I've also just done some testing and am not able to reproduce your results. 
First, I installed with the default settings, which installed jre16 as expected.

I then stopped the container, deleted the runtime folder, and changed `RUNTIME_NAME` to `basicjre`. despite this, the container still downloaded jre16
![image](https://user-images.githubusercontent.com/36567925/140720242-41b7959d-2375-4866-b015-3677da6a895e.png)
This image shows the current unraid configuration, with `RUNTIME_NAME` set to `basicjre`, the log after running this configuration, as well as a bash window showing that the runtime was removed before running.

**Comment by ich777** [comment]
@Airyzz oh, this is pretty odd, you've created the `RUNTIME_NAME` in the template, don't do it like that.
Please click on the `Show more settings...` text and you will see that this variable is already in there.
If you create it manually your variable will be overwritten by the one that already exist in the template under `Show more settings...` because it is actually appended later on to the `docker run` command.

![grafik](https://user-images.githubusercontent.com/28066518/140722678-2e0ba012-305f-4939-9c63-1e3c7729f68e.png)


I also would suggest that you use the unRAID support forum link for that if you are running the container on unRAID.
